name: PyCICD init
description: foo
author: Nicholas Valentinus
branding:
  icon: tool
  color: orange

inputs:
  BRANCH:
    description: 
    required: false

runs:
  using: 'node16'
  main: index.js