name: PyCICD
description: foo
author: Nicholas Valentinus
branding:
  icon: tool
  color: orange

inputs:
  foo:
    description: 
    required: true

runs:
  using: 'composite'
  steps:
    - run: ls
      shell: bash
    - uses: actions/checkout@v3
    - run: ls
      shell: bash
    - uses: ./.github/workflows/core.yml