name: PyCICD
description: foo
author: Nicholas Valentinus
branding:
  icon: tool
  color: orange

inputs:
  foo:
    description: 
    required: false

runs:
  using: 'composite'
  steps:
    - run: python $GITHUB_ACTION_PATH/engine/check_commit_msg.py
      shell: bash
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}