name: PyCICD
description: foo
author: Nicholas Valentinus
branding:
  icon: tool
  color: orange

inputs:
  foo:
    description: 
    required: true

runs:
  using: 'composite'
  steps:
    - uses: $GITHUB_ACTION_PATH/.github/workflows/core.yml